### PR TITLE
Pixel Order Options

### LINKED ISSUE #2: Swapped Color Data
Thank you for the useful library!

What's the reason that color order in the `OpcClient.WriteFrame()` method is swapped?
RGB is correct in my environment.

### PR DESCRIPTION
**Pull request by yutokun**
I found NeoPixels have two types of pixel order.
Most of all is GRB, but others are RGB.
http://www.seansworld.com/docs/arduino/adafruitReference.html

This PR let OPC will configure it.

### CODE REVIEW

**Comment by HunterCarlson** [comment]
Configurable + enum for options. I like it

**Comment by HunterCarlson** [comment]
@yutokun Thanks for doing your research and making it configurable instead of just swapping to always RGB order

**Comment by yutokun** [comment]
Thanks for such a warming comment!

**Comment by yutokun** [comment]
Thanks for such a warming comment!

**Pull request merged**
